### ISSUE TITLE
Upper damage limit is 1.099

### ISSUE THREAD

**Issue by gakiloroth** [maketakunai/maketakunai.github.io#2]
This is obviously a very small thing but I recently learned from the Atlas guys that the upper limit on damage is actually 1.099 and not 1.1 - although I believe some people apparently debate this. Just bringing this to your attention if you didn't already know😅

https://github.com/maketakunai/maketakunai.github.io/blob/c427c71c94a3eb109712b2088fd8bc6b2174c446/js/main.js#L204

**Comment by maketakunai** [comment]
Whoa! Thanks a bunch for letting me know - I had no idea. I'll change the value for the calc, then.

**Comment by gakiloroth** [comment]
Apparently this is the reason if you're curious at all:

https://docs.microsoft.com/en-us/dotnet/api/system.random.next?view=netframework-4.8#System_Random_Next_System_Int32_System_Int32_

I believe this is the damage calcs: (from atlas)
`float num8 = (float)BattleRandom.getRandom(ConstantMaster.getValue("ATTACK_RATE_RANDOM_MIN"), ConstantMaster.getValue("ATTACK_RATE_RANDOM_MAX")) / 1000f;`

And so the bottom is inclusive, top is exclusive from 900 to 1100

**Comment by maketakunai** [comment]
Aha, that would do it!
