### ISSUE TITLE
Add CE Attack as a Separate Field

### ISSUE THREAD

**Issue by balthanon** [maketakunai/maketakunai.github.io#4]
Given that the calculator overwrites the attack values when you update Servant or level, it would be nice if CE attack was separated out as its own field rather than needing to be added into the attack manually.  That way it would be easier to switch back and forth between different Servants to calculate differences, see how much damage you'll do at 90 vs 100 vs 110 vs 120, etc... without needing to constantly update the attack field manually.  

It will also serve as a useful reminder to people to actually include the attack value of the CE in the calculations.

(Might be interested in updating this myself if you don't have time.  It should be fairly straight forward.)

**Comment by maketakunai** [comment]
Oh hey - thanks for the suggestion!  Been kinda busy lately, but I'll see if I can get it added in sometime soon.

**Comment by balthanon** [comment]
Very nice, thanks for the update.
